captainVersion: 4
services:
  $$cap_appname-db:
    image: nikdi/cozyio-db
    environment:
      DB_USER: $$cap_appname-db-user
      DB_PASS: $$cap_appname-db-pass
    ports:
      - 5984:5984
    volumes:
      - $$cap_appname-db-data:/opt/couchdb/data
    networks:
      - app
    caproverExtra:
      notExposeAsWebApp: 'true'
  $$cap_appname-stack:
    image: nikdi/cozyio-server
    environment:
      DB_HOST: $$cap_appname-db
      DB_USER: $$cap_appname-db-user
      DB_PASS: $$cap_appname-db-pass
      DOMAIN: $$cap_appname-domain
      LOCALE: $$cap_appname-locale
      TIMEZONE: $$cap_appname-timezone
      COZY_PORT: $$cap_appname-cozy-port
      COZY_ADMIN_PORT: $$cap_appname-cozy-admin-port
      COZY_ADMIN_EMAIL: $$cap_appname-admin-email
      COZY_ADMIN_PASSWORD: $$cap_appname-admin-pass
      APPS: $$cap_appname-apps
    volumes:
      - $$cap_appname-cozy-data:/etc/cozy
    ports:
      - 3100:3100
      - 3200:3200
    networks:
      - app
    caproverExtra:
      containerHttpPort: '3100'
caproverOneClickApp:
  variables:
    - id: $$cap_appname-db-user
      label: DB Username
      defaultValue: cozy
    - id: $$cap_appname-db-pass
      label: DB Password
      defaultValue: cozypassword
    - id: $$cap_appname-domain
      label: App Domain
      defaultValue: $$cap_appname.$$cap_root_domain
    - id: $$cap_appname-locale
      label: Locale
      defaultValue: en
    - id: $$cap_appname-timezone
      label: TimeZone
      defaultValue: Europe/Moscow
    - id: $$cap_appname-cozy-port
      label: Cozy port
      defaultValue: '6100'
    - id: $$cap_appname-cozy-admin-port
      label: Cozy admin-panel port
      defaultValue: '6200'
    - id: $$cap_appname-admin-email
      label: Admin user E-Mail
    - id: $$cap_appname-admin-pass
      label: Admin user password
    - id: $$cap_appname-apps
      label: Apps list
      defaultValue: home,banks,contacts,drive,notes,passwords,photos,settings,store
  displayName: Cozy.io
  description: Cozy.io
  documentation: https://docs.cozy.io/
