captainVersion: 4
services:
    $$cap_appname:
        image: firezone/firezone:$$cap_firezone_version
        volumes:
            - $$cap_appname-data:/var/firezone
        restart: always
        depends-on: $$cap_appname-postgres
        command: "bin/server"
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        ports:
            - 0.0.0.0:51820:51820
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
            - net.ipv4.ip_forward=1
            - net.ipv6.conf.all.forwarding=1
        environment:
            EXTERNAL_URL: $$cap_appname.$$cap_root_domain
            DATABASE_HOST: $$cap_appname-postgres
            DATABASE_PORT: 5432
            DATABASE_NAME: postgres
            DATABASE_USER: app
            DATABASE_PASSWORD: app
            DEFAULT_ADMIN_EMAIL: $$cap_default_email
            DEFAULT_ADMIN_PASSWORD: $$cap_default_password
            GUARDIAN_SECRET_KEY: $$cap_guardian_key
            DATABASE_ENCRYPTION_KEY: $$cap_encryption_key
            SECRET_KEY_BASE: $$cap_secret_key
            LIVE_VIEW_SIGNING_SALT: $$cap_live_view_salt
            COOKIE_SIGNING_SALT: $$cap_cookie_signing_salt
            COOKIE_ENCRYPTION_SALT: $$cap_cookie_encryption_salt
        caproverExtra:
            containerHttpPort: '13000'
    $$cap_appname-postgres:
        image: postgres:$$cap_postgres_version
        volumes:
            - $$cap_appname-postgres-data:/data/postgres
        restart: always
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: app
            PGDATA: /data/postgres
        caproverExtra:
            notExposeAsWebApp: 'true'
caproverOneClickApp:
    variables:
        - id: $$cap_firezone_version
          label: Firezone Version Tag
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/firezone/firezone/tags
          defaultValue: 0.7.35
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_postgres_version
          label: Postgres Version Tag
          description: Check out their Docker page for the valid tags https://hub.docker.com/_/postgres/tags
          defaultValue: 15.4
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_default_email
          label: Default E-Mail
        - id: $$cap_default_password
          label: Default password
        - id: $$cap_guardian_key
          label: Guardian key
          description: More info https://www.firezone.dev/docs/reference/env-vars#secrets-and-encryption
        - id: $$cap_encryption_key
          label: Encryption key
          description: More info https://www.firezone.dev/docs/reference/env-vars#secrets-and-encryption
        - id: $$cap_secret_key
          label: Secret key
          description: More info https://www.firezone.dev/docs/reference/env-vars#secrets-and-encryption
        - id: $$cap_live_view_salt
          label: Live view salt
          description: More info https://www.firezone.dev/docs/reference/env-vars#secrets-and-encryption
        - id: $$cap_cookie_signing_salt
          label: Cookie signing salt
          description: More info https://www.firezone.dev/docs/reference/env-vars#secrets-and-encryption
        - id: $$cap_cookie_encryption_salt
          label: Cookie encryption salt
          description: More info https://www.firezone.dev/docs/reference/env-vars#secrets-and-encryption
    instructions:
        start: Hi!
        end: Firezone is deployed and available from the url http://$$cap_appname.$$cap_root_domain
    displayName: Firezone
    description: Firezone
    documentation: https://www.firezone.dev/docs
