captainVersion: 4
services:
  $$cap_appname:
    image: alekslitvinenk/openvpn
    volumes:
      - $$cap_appname-data:/opt/Dockovpn_data
      - $$cap_appname-config:/opt/Dockovpn/config
    restart: always
    environment:
      HOST_ADDR: $$cap_host_addr
      NET_ADAPTER: $$cap_net_adapter
    ports:
      - 1194:1194
    caproverExtra:
      containerHttpPort: '8080'
caproverOneClickApp:
  variables:
    - id: $$cap_host_addr
      label: Server IP
  variables:
    - id: $$cap_net_adapter
      label: Network adapter
  instructions:
    end: |
      OpenVPN is deployed. Config is available from the url http://$$cap_appname.$$cap_root_domain.
      Instructions::
        - Enable HTTPS
        - Enable force to HTTPS
      Then run:
      ```bash
      docker service scale srv-captain--$$cap_appname=0 && docker service update --cap-add NET_ADMIN srv-captain--$$cap_appname && docker service scale srv-captain--$$cap_appname=1
      ```
  displayName: OpenVPN
  description: OpenVPN
  documentation: https://dockovpn.io/docs/quickstart/
