name: Validate One Click Apps

on:
  push:
    branches:
      - none
  pull_request:
    branches:
      - none

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 1
      - run: npm ci && npm run validate_apps && npm run formatter
        env:
          GITHUB_PERSONAL_TOKEN: ${{secrets.GITHUB_PERSONAL_TOKEN}}
